{
    "backoff": 0,
    "has_more": true,
    "page": 1,
    "quota_max": 300,
    "quota_remaining": 259,
    "total": 0,
    "items": [
        {
            "tags": [
                "python",
                "error-handling",
                "pip",
                "debian"
            ],
            "owner": {
                "account_id": 23480036,
                "reputation": 5115,
                "user_id": 17532318,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/d37672946ecec10b2814be93daa910ef?s=256&d=identicon&r=PG",
                "display_name": "Apoliticalboy",
                "link": "https://stackoverflow.com/users/17532318/apoliticalboy"
            },
            "is_answered": true,
            "view_count": 855191,
            "protected_date": 1721306261,
            "answer_count": 29,
            "score": 497,
            "last_activity_date": 1721381729,
            "creation_date": 1677700339,
            "last_edit_date": 1721289366,
            "question_id": 75608323,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3",
            "title": "How do I solve &quot;error: externally-managed-environment&quot; every time I use pip 3?"
        },
        {
            "tags": [
                "python",
                "pandas",
                "dataframe",
                "attributeerror"
            ],
            "owner": {
                "account_id": 18651684,
                "reputation": 2921,
                "user_id": 13595011,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/a-/AOh14Gja1Bf3zfNP7LY4HSFgp6beG2pul2AVcXIsoLC52g=k-s256",
                "display_name": "Maksimjeet Chowdhary",
                "link": "https://stackoverflow.com/users/13595011/maksimjeet-chowdhary"
            },
            "is_answered": true,
            "view_count": 571455,
            "protected_date": 1695993982,
            "answer_count": 3,
            "score": 272,
            "last_activity_date": 1702932713,
            "creation_date": 1680851159,
            "last_edit_date": 1691967377,
            "question_id": 75956209,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/75956209/error-dataframe-object-has-no-attribute-append",
            "title": "Error &quot;&#39;DataFrame&#39; object has no attribute &#39;append&#39;&quot;"
        },
        {
            "tags": [
                "python",
                "macos",
                "terminal",
                "atom-editor",
                "macos-monterey"
            ],
            "owner": {
                "account_id": 24663681,
                "reputation": 3974,
                "user_id": 18559642,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/13cdab4eb9d9fb5b1c7dece549f96046?s=256&d=identicon&r=PG",
                "display_name": "Kirill Ignatyev",
                "link": "https://stackoverflow.com/users/18559642/kirill-ignatyev"
            },
            "is_answered": true,
            "view_count": 521962,
            "protected_date": 1673118234,
            "accepted_answer_id": 71621142,
            "answer_count": 18,
            "score": 238,
            "last_activity_date": 1717274629,
            "creation_date": 1648058522,
            "last_edit_date": 1656277606,
            "question_id": 71591971,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/71591971/how-can-i-fix-the-zsh-command-not-found-python-error-macos-monterey-12-3",
            "title": "How can I fix the &quot;zsh: command not found: python&quot; error? (macOS Monterey 12.3, Python&amp;nbsp;3.10, Atom IDE, and atom-python-run 0.9.7)"
        },
        {
            "tags": [
                "python",
                "tensorflow",
                "ray"
            ],
            "owner": {
                "account_id": 22989345,
                "reputation": 2161,
                "user_id": 17115086,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/16c137f7793988efb97ab410f7aec4f6?s=256&d=identicon&r=PG",
                "display_name": "hasu33",
                "link": "https://stackoverflow.com/users/17115086/hasu33"
            },
            "is_answered": true,
            "view_count": 340624,
            "protected_date": 1689017298,
            "answer_count": 17,
            "score": 211,
            "last_activity_date": 1704509020,
            "creation_date": 1653965255,
            "last_edit_date": 1656248470,
            "question_id": 72441758,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/72441758/typeerror-descriptors-cannot-not-be-created-directly",
            "title": "TypeError: Descriptors cannot not be created directly"
        },
        {
            "tags": [
                "python",
                "python-black"
            ],
            "owner": {
                "account_id": 13900281,
                "reputation": 12475,
                "user_id": 10036039,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/8790cbc891c02fffb597317b43a063fa?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "zerocewl",
                "link": "https://stackoverflow.com/users/10036039/zerocewl"
            },
            "is_answered": true,
            "view_count": 87816,
            "accepted_answer_id": 71674345,
            "answer_count": 6,
            "score": 183,
            "last_activity_date": 1701665110,
            "creation_date": 1648626375,
            "last_edit_date": 1651785651,
            "question_id": 71673404,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click",
            "title": "ImportError: cannot import name &#39;_unicodefun&#39; from &#39;click&#39;"
        },
        {
            "tags": [
                "python",
                "machine-learning",
                "package",
                "conda",
                "python-poetry"
            ],
            "owner": {
                "account_id": 1449869,
                "reputation": 3012,
                "user_id": 1367124,
                "user_type": "registered",
                "accept_rate": 68,
                "profile_image": "https://i.sstatic.net/azGrD.jpg?s=256",
                "display_name": "Seub",
                "link": "https://stackoverflow.com/users/1367124/seub"
            },
            "is_answered": true,
            "view_count": 87402,
            "accepted_answer_id": 71110028,
            "answer_count": 4,
            "score": 181,
            "last_activity_date": 1712340837,
            "creation_date": 1643123383,
            "last_edit_date": 1643126235,
            "question_id": 70851048,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/70851048/does-it-make-sense-to-use-conda-poetry",
            "title": "Does it make sense to use Conda + Poetry?"
        },
        {
            "tags": [
                "python",
                "flask",
                "pytest",
                "werkzeug"
            ],
            "owner": {
                "account_id": 20745029,
                "reputation": 2372,
                "user_id": 15233792,
                "user_type": "registered",
                "profile_image": "https://i.sstatic.net/2ol6b.jpg?s=256",
                "display_name": "stevezkw",
                "link": "https://stackoverflow.com/users/15233792/stevezkw"
            },
            "is_answered": true,
            "view_count": 157570,
            "protected_date": 1698079880,
            "accepted_answer_id": 77214086,
            "answer_count": 6,
            "score": 177,
            "last_activity_date": 1708084399,
            "creation_date": 1696215720,
            "last_edit_date": 1700174126,
            "question_id": 77213053,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/77213053/why-did-flask-start-failing-with-importerror-cannot-import-name-url-quote-fr",
            "title": "Why did Flask start failing with &quot;ImportError: cannot import name &#39;url_quote&#39; from &#39;werkzeug.urls&#39;&quot;?"
        },
        {
            "tags": [
                "python",
                "google-analytics-api"
            ],
            "owner": {
                "account_id": 6468208,
                "reputation": 6877,
                "user_id": 5009293,
                "user_type": "registered",
                "accept_rate": 76,
                "profile_image": "https://graph.facebook.com/995762863775266/picture?type=large",
                "display_name": "Doug Coats",
                "link": "https://stackoverflow.com/users/5009293/doug-coats"
            },
            "is_answered": true,
            "view_count": 291962,
            "accepted_answer_id": 73932621,
            "answer_count": 21,
            "score": 169,
            "last_activity_date": 1712734945,
            "creation_date": 1663949925,
            "last_edit_date": 1704753149,
            "question_id": 73830524,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/73830524/attributeerror-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check",
            "title": "AttributeError: module &#39;lib&#39; has no attribute &#39;X509_V_FLAG_CB_ISSUER_CHECK&#39;"
        },
        {
            "tags": [
                "python",
                "pandas",
                "dataframe",
                "data-wrangling",
                "data-munging"
            ],
            "owner": {
                "account_id": 29727,
                "reputation": 4823,
                "user_id": 80544,
                "user_type": "registered",
                "accept_rate": 79,
                "profile_image": "https://i.sstatic.net/HtN07.jpg?s=256",
                "display_name": "Glenn",
                "link": "https://stackoverflow.com/users/80544/glenn"
            },
            "is_answered": true,
            "view_count": 218343,
            "accepted_answer_id": 70837545,
            "answer_count": 9,
            "score": 164,
            "last_activity_date": 1719313086,
            "creation_date": 1643042804,
            "last_edit_date": 1645482240,
            "question_id": 70837397,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/70837397/good-alternative-to-pandas-append-method-now-that-it-is-being-deprecated",
            "title": "Good alternative to Pandas .append() method, now that it is being deprecated?"
        },
        {
            "tags": [
                "python",
                "prompt",
                "openai-api",
                "completion",
                "chatgpt-api"
            ],
            "owner": {
                "account_id": 3235065,
                "reputation": 2420,
                "user_id": 3018860,
                "user_type": "registered",
                "accept_rate": 89,
                "profile_image": "https://www.gravatar.com/avatar/edec84abcde58e8f5d45a7e5522ff1e1?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "Unix",
                "link": "https://stackoverflow.com/users/3018860/unix"
            },
            "is_answered": true,
            "view_count": 342581,
            "closed_date": 1685124780,
            "accepted_answer_id": 75898717,
            "answer_count": 5,
            "score": 156,
            "last_activity_date": 1704422130,
            "creation_date": 1680263884,
            "last_edit_date": 1704294387,
            "question_id": 75898276,
            "link": "https://stackoverflow.com/questions/75898276/openai-api-error-429-you-exceeded-your-current-quota-please-check-your-plan-a",
            "closed_reason": "Not suitable for this site",
            "title": "OpenAI API error 429: &quot;You exceeded your current quota, please check your plan and billing details&quot;"
        },
        {
            "tags": [
                "python",
                "openai-api",
                "urllib3"
            ],
            "owner": {
                "account_id": 11229285,
                "reputation": 1523,
                "user_id": 8237910,
                "user_type": "registered",
                "profile_image": "https://lh5.googleusercontent.com/-OajeBMxDGMo/AAAAAAAAAAI/AAAAAAAAAmQ/8vm8L0FQK1c/photo.jpg?sz=256",
                "display_name": "prismwatermelon",
                "link": "https://stackoverflow.com/users/8237910/prismwatermelon"
            },
            "is_answered": true,
            "view_count": 333164,
            "accepted_answer_id": 76187415,
            "answer_count": 15,
            "score": 142,
            "last_activity_date": 1718346595,
            "creation_date": 1683349902,
            "last_edit_date": 1691972425,
            "question_id": 76187256,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/76187256/importerror-urllib3-v2-0-only-supports-openssl-1-1-1-currently-the-ssl-modu",
            "title": "ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the &#39;ssl&#39; module is compiled with LibreSSL 2.8.3"
        },
        {
            "tags": [
                "python",
                "python-3.x",
                "pip"
            ],
            "owner": {
                "account_id": 6714573,
                "reputation": 1631,
                "user_id": 6323020,
                "user_type": "registered",
                "accept_rate": 50,
                "profile_image": "https://www.gravatar.com/avatar/ca1065f7cc55d81ea1ea374b14113ac4?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "sreeraj t",
                "link": "https://stackoverflow.com/users/6323020/sreeraj-t"
            },
            "is_answered": true,
            "view_count": 173753,
            "protected_date": 1712051464,
            "accepted_answer_id": 77364602,
            "answer_count": 7,
            "score": 135,
            "last_activity_date": 1721889268,
            "creation_date": 1698301344,
            "last_edit_date": 1704602075,
            "question_id": 77364550,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean",
            "title": "AttributeError: module &#39;pkgutil&#39; has no attribute &#39;ImpImporter&#39;. Did you mean: &#39;zipimporter&#39;?"
        },
        {
            "tags": [
                "python",
                "docker",
                "docker-compose",
                "dependencies",
                "importerror"
            ],
            "owner": {
                "account_id": 3369545,
                "reputation": 3421,
                "user_id": 2829150,
                "user_type": "registered",
                "accept_rate": 51,
                "profile_image": "https://www.gravatar.com/avatar/1e9c788890b3d2a8e468ed2773864b2c?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "Arie",
                "link": "https://stackoverflow.com/users/2829150/arie"
            },
            "is_answered": true,
            "view_count": 188876,
            "protected_date": 1691442712,
            "answer_count": 15,
            "score": 132,
            "last_activity_date": 1699634829,
            "creation_date": 1652208276,
            "last_edit_date": 1667754370,
            "question_id": 72191560,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/72191560/importerror-cannot-import-name-soft-unicode-from-markupsafe",
            "title": "ImportError: cannot import name &#39;soft_unicode&#39; from &#39;markupsafe&#39;"
        },
        {
            "tags": [
                "python",
                "selenium",
                "google-chrome",
                "selenium-webdriver",
                "selenium-chromedriver"
            ],
            "owner": {
                "account_id": 19488994,
                "reputation": 1413,
                "user_id": 14257612,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/c49440f3d6f3831211bcb56d9614a61e?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "Alesss",
                "link": "https://stackoverflow.com/users/14257612/alesss"
            },
            "is_answered": true,
            "view_count": 299406,
            "accepted_answer_id": 72773269,
            "answer_count": 5,
            "score": 131,
            "last_activity_date": 1710334533,
            "creation_date": 1656337711,
            "last_edit_date": 1661689426,
            "question_id": 72773206,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/72773206/selenium-python-attributeerror-webdriver-object-has-no-attribute-find-el",
            "title": "Selenium - Python - AttributeError: &#39;WebDriver&#39; object has no attribute &#39;find_element_by_name&#39;"
        },
        {
            "tags": [
                "python",
                "linux",
                "openssl",
                "python-poetry"
            ],
            "owner": {
                "account_id": 7489950,
                "reputation": 5116,
                "user_id": 5692012,
                "user_type": "registered",
                "accept_rate": 50,
                "profile_image": "https://i.sstatic.net/a3FwR.gif?s=256",
                "display_name": "RobinFrcd",
                "link": "https://stackoverflow.com/users/5692012/robinfrcd"
            },
            "is_answered": true,
            "view_count": 266917,
            "accepted_answer_id": 72633324,
            "answer_count": 16,
            "score": 127,
            "last_activity_date": 1719316127,
            "creation_date": 1651782719,
            "last_edit_date": 1675089528,
            "question_id": 72133316,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory",
            "title": "libssl.so.1.1: cannot open shared object file: No such file or directory"
        },
        {
            "tags": [
                "python",
                "linux"
            ],
            "owner": {
                "account_id": 27907651,
                "reputation": 1369,
                "user_id": 21310501,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/a/AGNmyxb3a8PSNvhapdvFSFi0i8vX_XG9vbYoqiUUjBzk=k-s256",
                "display_name": "iReXes ",
                "link": "https://stackoverflow.com/users/21310501/irexes"
            },
            "is_answered": true,
            "view_count": 326474,
            "closed_date": 1719028471,
            "answer_count": 12,
            "score": 126,
            "last_activity_date": 1718042011,
            "creation_date": 1677664429,
            "last_edit_date": 1694076936,
            "question_id": 75602063,
            "link": "https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-mana",
            "closed_reason": "Duplicate",
            "title": "pip install -r requirements.txt is failing: &quot;This environment is externally managed&quot;"
        },
        {
            "tags": [
                "python",
                "windows",
                "visual-studio-2022"
            ],
            "owner": {
                "account_id": 2813476,
                "reputation": 1843,
                "user_id": 2419205,
                "user_type": "registered",
                "accept_rate": 52,
                "profile_image": "https://www.gravatar.com/avatar/5a4b5ff5c0d06ba079e8d974dd8309b4?s=256&d=identicon&r=PG",
                "display_name": "Starfleet Security",
                "link": "https://stackoverflow.com/users/2419205/starfleet-security"
            },
            "is_answered": true,
            "view_count": 7664,
            "answer_count": 9,
            "score": 107,
            "last_activity_date": 1668277374,
            "creation_date": 1645204638,
            "last_edit_date": 1648802107,
            "question_id": 71177450,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/71177450/unable-to-restore-visual-studio-2022-window-ide-itself-after-minimizing",
            "title": "Unable to restore Visual Studio 2022 window (IDE itself) after minimizing"
        },
        {
            "tags": [
                "python",
                "python-typing"
            ],
            "owner": {
                "account_id": 1881254,
                "reputation": 1718,
                "user_id": 1701415,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/cb5160e829bd4a3a0863e8bd6cff9aea?s=256&d=identicon&r=PG",
                "display_name": "Jesse",
                "link": "https://stackoverflow.com/users/1701415/jesse"
            },
            "is_answered": true,
            "view_count": 67233,
            "accepted_answer_id": 76399911,
            "answer_count": 5,
            "score": 103,
            "last_activity_date": 1715273271,
            "creation_date": 1650158620,
            "question_id": 71898644,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/71898644/how-to-use-python-typing-annotated",
            "title": "How to use python typing.Annotated?"
        },
        {
            "tags": [
                "python",
                "pip"
            ],
            "owner": {
                "account_id": 15449541,
                "reputation": 1189,
                "user_id": 17660775,
                "user_type": "registered",
                "profile_image": "https://graph.facebook.com/2328891030722501/picture?type=large",
                "display_name": "Abdeldjalil Sekkal",
                "link": "https://stackoverflow.com/users/17660775/abdeldjalil-sekkal"
            },
            "is_answered": true,
            "view_count": 200667,
            "protected_date": 1676571122,
            "answer_count": 11,
            "score": 102,
            "last_activity_date": 1714268093,
            "creation_date": 1653937478,
            "last_edit_date": 1702941130,
            "question_id": 72439001,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/72439001/there-was-an-error-checking-the-latest-version-of-pip",
            "title": "There was an error checking the latest version of pip"
        },
        {
            "tags": [
                "python",
                "string",
                "reference",
                "immutability",
                "string-concatenation"
            ],
            "owner": {
                "account_id": 6666507,
                "reputation": 1245,
                "user_id": 5144013,
                "user_type": "registered",
                "accept_rate": 44,
                "profile_image": "https://lh3.googleusercontent.com/-gaua46VyxKQ/AAAAAAAAAAI/AAAAAAAAHxg/M-29RPq_C6E/photo.jpg?sz=256",
                "display_name": "Master_Roshy",
                "link": "https://stackoverflow.com/users/5144013/master-roshy"
            },
            "is_answered": true,
            "view_count": 7099,
            "protected_date": 1657262192,
            "answer_count": 4,
            "score": 102,
            "last_activity_date": 1657261330,
            "creation_date": 1654830500,
            "last_edit_date": 1654982358,
            "question_id": 72568719,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/72568719/if-python-strings-are-immutable-why-does-it-keep-the-same-id-if-i-use-to-app",
            "title": "If Python strings are immutable, why does it keep the same id if I use += to append to it?"
        },
        {
            "tags": [
                "python",
                "cpython",
                "python-internals"
            ],
            "owner": {
                "account_id": 17476274,
                "reputation": 27057,
                "user_id": 12671057,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/90d2e6942c69df199a95d06e0c8e9a10?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "Kelly Bundy",
                "link": "https://stackoverflow.com/users/12671057/kelly-bundy"
            },
            "is_answered": true,
            "view_count": 8510,
            "closed_date": 1643494282,
            "accepted_answer_id": 70882093,
            "answer_count": 3,
            "score": 101,
            "last_activity_date": 1644084297,
            "creation_date": 1643300597,
            "last_edit_date": 1644083484,
            "question_id": 70882092,
            "link": "https://stackoverflow.com/questions/70882092/can-we-make-1-2-true",
            "closed_reason": "Duplicate",
            "title": "Can we make 1 == 2 true?"
        },
        {
            "tags": [
                "python",
                "ubuntu",
                "pip",
                "windows-subsystem-for-linux"
            ],
            "owner": {
                "account_id": 7752222,
                "reputation": 1205,
                "user_id": 6799513,
                "user_type": "registered",
                "profile_image": "https://i.sstatic.net/Bha40.jpg?s=256",
                "display_name": "patrick",
                "link": "https://stackoverflow.com/users/6799513/patrick"
            },
            "is_answered": true,
            "view_count": 99650,
            "accepted_answer_id": 75053968,
            "answer_count": 4,
            "score": 100,
            "last_activity_date": 1702742218,
            "creation_date": 1672657056,
            "last_edit_date": 1672657567,
            "question_id": 74981558,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/74981558/error-updating-python3-pip-attributeerror-module-lib-has-no-attribute-openss",
            "title": "Error Updating Python3 pip AttributeError: module &#39;lib&#39; has no attribute &#39;OpenSSL_add_all_algorithms&#39;"
        },
        {
            "tags": [
                "python",
                "python-imaging-library"
            ],
            "owner": {
                "account_id": 26367272,
                "reputation": 1084,
                "user_id": 20022511,
                "user_type": "registered",
                "profile_image": "https://i.sstatic.net/zvtp5.png?s=256",
                "display_name": "MT_276",
                "link": "https://stackoverflow.com/users/20022511/mt-276"
            },
            "is_answered": true,
            "view_count": 157549,
            "accepted_answer_id": 76616129,
            "answer_count": 8,
            "score": 97,
            "last_activity_date": 1707502695,
            "creation_date": 1688507881,
            "last_edit_date": 1704562499,
            "question_id": 76616042,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias",
            "title": "AttributeError: module &#39;PIL.Image&#39; has no attribute &#39;ANTIALIAS&#39;"
        },
        {
            "tags": [
                "python",
                "ffmpeg",
                "discord",
                "youtube-dl"
            ],
            "owner": {
                "account_id": 27587346,
                "reputation": 907,
                "user_id": 21055247,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/a/AEdFTp68sX4uwH8oI00wq1qnsHwmhUC3m9kFQUea4JSE=k-s256",
                "display_name": "nikita goncharov",
                "link": "https://stackoverflow.com/users/21055247/nikita-goncharov"
            },
            "is_answered": true,
            "view_count": 113399,
            "accepted_answer_id": 75504772,
            "answer_count": 10,
            "score": 88,
            "last_activity_date": 1721680970,
            "creation_date": 1676747963,
            "last_edit_date": 1700757654,
            "question_id": 75495800,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/75495800/error-unable-to-extract-uploader-id-youtube-discord-py",
            "title": "Error: Unable to extract uploader id - Youtube, Discord.py"
        },
        {
            "tags": [
                "python",
                "c++",
                "python-3.x",
                "rounding",
                "integer-division"
            ],
            "owner": {
                "account_id": 7923772,
                "reputation": 7356,
                "user_id": 5983841,
                "user_type": "registered",
                "accept_rate": 62,
                "profile_image": "https://i.sstatic.net/GHJxG.jpg?s=256",
                "display_name": "Rick",
                "link": "https://stackoverflow.com/users/5983841/rick"
            },
            "is_answered": true,
            "view_count": 8623,
            "accepted_answer_id": 70735005,
            "answer_count": 8,
            "score": 88,
            "last_activity_date": 1660790087,
            "creation_date": 1642342052,
            "last_edit_date": 1643506145,
            "question_id": 70730831,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/70730831/whats-the-mathematical-reason-behind-python-choosing-to-round-integer-division",
            "title": "What&#39;s the mathematical reason behind Python choosing to round integer division toward negative infinity?"
        },
        {
            "tags": [
                "python",
                "python-3.x",
                "pip"
            ],
            "owner": {
                "account_id": 23650540,
                "reputation": 895,
                "user_id": 17679479,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/a-/AOh14Gir3m-DTE1Yx2GwtNYJ0w02mRyRj-8yB5ZPmIx5=k-s256",
                "display_name": "BRICK MANE",
                "link": "https://stackoverflow.com/users/17679479/brick-mane"
            },
            "is_answered": true,
            "view_count": 184728,
            "answer_count": 16,
            "score": 83,
            "last_activity_date": 1716886023,
            "creation_date": 1643729700,
            "last_edit_date": 1658994516,
            "question_id": 70943244,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/70943244/attributeerror-module-collections-has-no-attribute-mutablemapping",
            "title": "AttributeError: module &#39;collections&#39; has no attribute &#39;MutableMapping&#39;"
        },
        {
            "tags": [
                "python",
                "python-typing"
            ],
            "owner": {
                "account_id": 24765622,
                "reputation": 1248,
                "user_id": 18649495,
                "user_type": "registered",
                "profile_image": "https://i.sstatic.net/tG5JN.jpg?s=256",
                "display_name": "Fed_Dragon",
                "link": "https://stackoverflow.com/users/18649495/fed-dragon"
            },
            "is_answered": true,
            "view_count": 25181,
            "accepted_answer_id": 72158086,
            "answer_count": 3,
            "score": 82,
            "last_activity_date": 1721427446,
            "creation_date": 1651970217,
            "last_edit_date": 1721427446,
            "question_id": 72157296,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/72157296/what-is-the-difference-between-type-hinting-a-variable-as-an-iterable-versus-a-s",
            "title": "What is the difference between type-hinting a variable as an Iterable versus a Sequence?"
        },
        {
            "tags": [
                "python",
                "ssl",
                "openssl",
                "runtime-error"
            ],
            "owner": {
                "account_id": 17018517,
                "reputation": 921,
                "user_id": 12311729,
                "user_type": "registered",
                "profile_image": "https://graph.facebook.com/2152598004840080/picture?type=large",
                "display_name": "Gianmarco Broilo",
                "link": "https://stackoverflow.com/users/12311729/gianmarco-broilo"
            },
            "is_answered": true,
            "view_count": 194070,
            "protected_date": 1720117247,
            "accepted_answer_id": 72374542,
            "answer_count": 12,
            "score": 81,
            "last_activity_date": 1719931665,
            "creation_date": 1648128152,
            "last_edit_date": 1700615763,
            "question_id": 71603314,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled",
            "title": "SSL error unsafe legacy renegotiation disabled"
        },
        {
            "tags": [
                "python",
                "python-poetry"
            ],
            "owner": {
                "account_id": 5622044,
                "reputation": 9113,
                "user_id": 4451521,
                "user_type": "registered",
                "accept_rate": 34,
                "profile_image": "https://www.gravatar.com/avatar/4b19b54142d820aad565ca95f920c11c?s=256&d=identicon&r=PG",
                "display_name": "KansaiRobot",
                "link": "https://stackoverflow.com/users/4451521/kansairobot"
            },
            "is_answered": true,
            "view_count": 53888,
            "answer_count": 5,
            "score": 81,
            "last_activity_date": 1720703794,
            "creation_date": 1675940902,
            "question_id": 75397736,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/75397736/poetry-install-on-an-existing-project-error-does-not-contain-any-element",
            "title": "Poetry install on an existing project Error &quot;does not contain any element&quot;"
        },
        {
            "tags": [
                "python",
                "pre-commit",
                "pre-commit.com",
                "isort"
            ],
            "owner": {
                "account_id": 8247924,
                "reputation": 6315,
                "user_id": 6203472,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/6854a8b5ed6ad561c0ab878c7558fb26?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "bagerard",
                "link": "https://stackoverflow.com/users/6203472/bagerard"
            },
            "is_answered": true,
            "view_count": 16311,
            "accepted_answer_id": 75269701,
            "answer_count": 5,
            "score": 79,
            "last_activity_date": 1678725721,
            "creation_date": 1674928449,
            "last_edit_date": 1675093819,
            "question_id": 75269700,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/75269700/pre-commit-fails-to-install-isort-5-11-4-with-error-runtimeerror-the-poetry-co",
            "title": "pre-commit fails to install isort 5.11.4 with error &quot;RuntimeError: The Poetry configuration is invalid&quot;"
        },
        {
            "tags": [
                "python",
                "django",
                "digital-ocean"
            ],
            "owner": {
                "account_id": 8967886,
                "reputation": 3950,
                "user_id": 6687699,
                "user_type": "registered",
                "accept_rate": 58,
                "profile_image": "https://i.sstatic.net/4Snxy.jpg?s=256",
                "display_name": "Lutaaya Huzaifah Idris",
                "link": "https://stackoverflow.com/users/6687699/lutaaya-huzaifah-idris"
            },
            "is_answered": true,
            "view_count": 50329,
            "accepted_answer_id": 73932581,
            "answer_count": 6,
            "score": 77,
            "last_activity_date": 1704807596,
            "creation_date": 1664747002,
            "question_id": 73929564,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean",
            "title": "&#39;EntryPoints&#39; object has no attribute &#39;get&#39; - Digital ocean"
        },
        {
            "tags": [
                "python",
                "performance",
                "comparison"
            ],
            "owner": {
                "account_id": 393493,
                "reputation": 5031,
                "user_id": 755371,
                "user_type": "registered",
                "accept_rate": 44,
                "profile_image": "https://i.sstatic.net/Cmp2K.png?s=256",
                "display_name": "Eric",
                "link": "https://stackoverflow.com/users/755371/eric"
            },
            "is_answered": true,
            "view_count": 8218,
            "closed_date": 1648640765,
            "accepted_answer_id": 71644988,
            "answer_count": 2,
            "score": 77,
            "last_activity_date": 1648641525,
            "creation_date": 1648455910,
            "last_edit_date": 1648563343,
            "question_id": 71644405,
            "link": "https://stackoverflow.com/questions/71644405/why-is-it-faster-to-compare-strings-that-match-than-strings-that-do-not",
            "closed_reason": "Duplicate",
            "title": "Why is it faster to compare strings that match than strings that do not?"
        },
        {
            "tags": [
                "python",
                "openai-api",
                "chatgpt-api",
                "gpt-3",
                "gpt-4"
            ],
            "owner": {
                "account_id": 5699987,
                "reputation": 1404,
                "user_id": 4505301,
                "user_type": "registered",
                "profile_image": "https://i.sstatic.net/Zko8X.jpg?s=256",
                "display_name": "meliksahturker",
                "link": "https://stackoverflow.com/users/4505301/meliksahturker"
            },
            "is_answered": true,
            "view_count": 78522,
            "accepted_answer_id": 75804651,
            "answer_count": 4,
            "score": 77,
            "last_activity_date": 1716198456,
            "creation_date": 1679420110,
            "last_edit_date": 1712708782,
            "question_id": 75804599,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/75804599/openai-api-how-do-i-count-tokens-before-i-send-an-api-request",
            "title": "OpenAI API: How do I count tokens before(!) I send an API request?"
        },
        {
            "tags": [
                "python",
                "tensorflow",
                "conda",
                "apple-m1"
            ],
            "owner": {
                "account_id": 114708,
                "reputation": 11689,
                "user_id": 301513,
                "user_type": "registered",
                "accept_rate": 47,
                "profile_image": "https://i.sstatic.net/oWFRY.png?s=256",
                "display_name": "Qiulang",
                "link": "https://stackoverflow.com/users/301513/qiulang"
            },
            "is_answered": true,
            "view_count": 85025,
            "protected_date": 1694544271,
            "answer_count": 15,
            "score": 77,
            "last_activity_date": 1702108628,
            "creation_date": 1657708328,
            "last_edit_date": 1695005358,
            "question_id": 72964800,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/72964800/what-is-the-proper-way-to-install-tensorflow-on-apple-m1-in-2022",
            "title": "What is the proper way to install TensorFlow on Apple M1 in 2022"
        },
        {
            "tags": [
                "python",
                "enums",
                "f-string"
            ],
            "owner": {
                "account_id": 10991861,
                "reputation": 6534,
                "user_id": 8075540,
                "user_type": "registered",
                "profile_image": "https://i.sstatic.net/0eZhT.jpg?s=256",
                "display_name": "Daniel Walker",
                "link": "https://stackoverflow.com/users/8075540/daniel-walker"
            },
            "is_answered": true,
            "view_count": 9558,
            "accepted_answer_id": 72449614,
            "answer_count": 2,
            "score": 74,
            "last_activity_date": 1693593159,
            "creation_date": 1654006677,
            "last_edit_date": 1660255156,
            "question_id": 72449482,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/72449482/f-string-representation-different-than-str",
            "title": "f-string representation different than str()"
        },
        {
            "tags": [
                "python",
                "pip",
                "setuptools",
                "pyproject.toml"
            ],
            "owner": {
                "account_id": 2017134,
                "reputation": 25626,
                "user_id": 1804173,
                "user_type": "registered",
                "accept_rate": 77,
                "profile_image": "https://www.gravatar.com/avatar/53f721a451a1c68caf8316cefcde3083?s=256&d=identicon&r=PG",
                "display_name": "bluenote10",
                "link": "https://stackoverflow.com/users/1804173/bluenote10"
            },
            "is_answered": true,
            "view_count": 38310,
            "accepted_answer_id": 73600610,
            "answer_count": 2,
            "score": 74,
            "last_activity_date": 1718434604,
            "creation_date": 1662300788,
            "last_edit_date": 1667985506,
            "question_id": 73600082,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/73600082/how-to-reference-a-requirements-txt-in-the-pyproject-toml-of-a-setuptools-projec",
            "title": "How to reference a requirements.txt in the pyproject.toml of a setuptools project?"
        },
        {
            "tags": [
                "python",
                "docker",
                "flask",
                "docker-compose"
            ],
            "owner": {
                "account_id": 22335364,
                "reputation": 894,
                "user_id": 16556045,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/a-/AOh14GitmoVYWKb7Xize5hPMshSWNoFyMKSumgrMWNBXBA=k-s256",
                "display_name": "KronosHedronos2077",
                "link": "https://stackoverflow.com/users/16556045/kronoshedronos2077"
            },
            "is_answered": true,
            "view_count": 81514,
            "accepted_answer_id": 71219718,
            "answer_count": 11,
            "score": 70,
            "last_activity_date": 1691078711,
            "creation_date": 1645310480,
            "last_edit_date": 1663178530,
            "question_id": 71189819,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/71189819/importerror-cannot-import-name-json-from-itsdangerous",
            "title": "ImportError: cannot import name &#39;json&#39; from itsdangerous"
        },
        {
            "tags": [
                "python",
                "django",
                "heroku"
            ],
            "owner": {
                "account_id": 16660311,
                "reputation": 789,
                "user_id": 12040445,
                "user_type": "registered",
                "profile_image": "https://i.sstatic.net/ydOnG.jpg?s=256",
                "display_name": "SarveshJoshi",
                "link": "https://stackoverflow.com/users/12040445/sarveshjoshi"
            },
            "is_answered": true,
            "view_count": 104164,
            "accepted_answer_id": 72796492,
            "answer_count": 11,
            "score": 69,
            "last_activity_date": 1697317485,
            "creation_date": 1648843469,
            "question_id": 71712258,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/71712258/error-could-not-build-wheels-for-backports-zoneinfo-which-is-required-to-insta",
            "title": "ERROR: Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based projects"
        },
        {
            "tags": [
                "python",
                "json",
                "dictionary",
                "python-dataclasses"
            ],
            "owner": {
                "account_id": 14841576,
                "reputation": 1098,
                "user_id": 10718164,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/acc4f37c0049f3694dd50ae7b9a463a5?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "Unknown",
                "link": "https://stackoverflow.com/users/10718164/unknown"
            },
            "is_answered": true,
            "view_count": 100063,
            "accepted_answer_id": 72605423,
            "answer_count": 4,
            "score": 68,
            "last_activity_date": 1712378529,
            "creation_date": 1655132088,
            "last_edit_date": 1655132451,
            "question_id": 72604922,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/72604922/how-to-convert-python-dataclass-to-dictionary-of-string-literal",
            "title": "How to convert Python dataclass to dictionary of string literal?"
        },
        {
            "tags": [
                "python",
                "python-poetry"
            ],
            "owner": {
                "account_id": 442058,
                "reputation": 235,
                "user_id": 832490,
                "user_type": "registered",
                "accept_rate": 100,
                "profile_image": "https://www.gravatar.com/avatar/38de998f10120ac8f0dab7f193bedf2b?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "Rodrigo",
                "link": "https://stackoverflow.com/users/832490/rodrigo"
            },
            "is_answered": true,
            "view_count": 51207,
            "accepted_answer_id": 72547402,
            "answer_count": 2,
            "score": 68,
            "last_activity_date": 1721813402,
            "creation_date": 1652898582,
            "last_edit_date": 1652904288,
            "question_id": 72294299,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/72294299/multiple-top-level-packages-discovered-in-a-flat-layout",
            "title": "Multiple top-level packages discovered in a flat-layout"
        },
        {
            "tags": [
                "python",
                "asynchronous",
                "python-asyncio",
                "fastapi",
                "concurrent-processing"
            ],
            "owner": {
                "account_id": 1237641,
                "reputation": 2512,
                "user_id": 1200914,
                "user_type": "registered",
                "accept_rate": 89,
                "profile_image": "https://www.gravatar.com/avatar/d3c21d029de13a98c973b98f28ad6867?s=256&d=identicon&r=PG",
                "display_name": "Learning from masters",
                "link": "https://stackoverflow.com/users/1200914/learning-from-masters"
            },
            "is_answered": true,
            "view_count": 58511,
            "protected_date": 1685986311,
            "accepted_answer_id": 71517830,
            "answer_count": 3,
            "score": 67,
            "last_activity_date": 1721805345,
            "creation_date": 1647535766,
            "last_edit_date": 1650812721,
            "question_id": 71516140,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/71516140/fastapi-runs-api-calls-in-serial-instead-of-parallel-fashion",
            "title": "FastAPI runs api-calls in serial instead of parallel fashion"
        },
        {
            "tags": [
                "python",
                "numpy"
            ],
            "owner": {
                "account_id": 12810242,
                "reputation": 924,
                "user_id": 9481479,
                "user_type": "registered",
                "profile_image": "https://graph.facebook.com/1769985833305230/picture?type=large",
                "display_name": "Nawin K Sharma",
                "link": "https://stackoverflow.com/users/9481479/nawin-k-sharma"
            },
            "is_answered": true,
            "view_count": 142545,
            "accepted_answer_id": 74861894,
            "answer_count": 8,
            "score": 67,
            "last_activity_date": 1706669762,
            "creation_date": 1671396136,
            "last_edit_date": 1677183023,
            "question_id": 74844262,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/74844262/how-can-i-solve-error-module-numpy-has-no-attribute-float-in-python",
            "title": "How can I solve error &quot;module &#39;numpy&#39; has no attribute &#39;float&#39;&quot; in Python?"
        },
        {
            "tags": [
                "python",
                "ipython"
            ],
            "owner": {
                "account_id": 3582471,
                "reputation": 2921,
                "user_id": 2990344,
                "user_type": "registered",
                "accept_rate": 69,
                "profile_image": "https://www.gravatar.com/avatar/a3f9a2172c31b0a956c093d24230facd?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "xdavidliu",
                "link": "https://stackoverflow.com/users/2990344/xdavidliu"
            },
            "is_answered": true,
            "view_count": 11717,
            "accepted_answer_id": 71459528,
            "answer_count": 3,
            "score": 67,
            "last_activity_date": 1714070853,
            "creation_date": 1644771035,
            "question_id": 71102876,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/71102876/in-ipython-how-do-i-accept-and-use-an-autocomplete-suggestion",
            "title": "in ipython how do I accept and use an autocomplete suggestion?"
        },
        {
            "tags": [
                "python",
                "amazon-web-services",
                "amazon-s3",
                "aws-lambda",
                "boto3"
            ],
            "owner": {
                "account_id": 5059080,
                "reputation": 2913,
                "user_id": 4061339,
                "user_type": "registered",
                "accept_rate": 70,
                "profile_image": "https://i.sstatic.net/HeGDO.png?s=256",
                "display_name": "dixhom",
                "link": "https://stackoverflow.com/users/4061339/dixhom"
            },
            "is_answered": true,
            "view_count": 91905,
            "accepted_answer_id": 76422261,
            "answer_count": 13,
            "score": 65,
            "last_activity_date": 1720681322,
            "creation_date": 1686053443,
            "question_id": 76414514,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/76414514/cannot-import-name-default-ciphers-from-urllib3-util-ssl-on-aws-lambda-us",
            "title": "&quot;cannot import name &#39;DEFAULT_CIPHERS&#39; from &#39;urllib3.util.ssl_&#39;&quot; on AWS Lambda using a layer"
        },
        {
            "tags": [
                "python",
                "swift",
                "xcode"
            ],
            "owner": {
                "account_id": 30677402,
                "reputation": 705,
                "user_id": 23519070,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/a/ACg8ocLZxBb5di_42wV3YgLeHeZclOX0bWtz1lY9cKm5JB1Po_c=k-s256",
                "display_name": "James Menkal",
                "link": "https://stackoverflow.com/users/23519070/james-menkal"
            },
            "is_answered": true,
            "view_count": 38369,
            "protected_date": 1718421403,
            "accepted_answer_id": 78204720,
            "answer_count": 4,
            "score": 65,
            "last_activity_date": 1719986022,
            "creation_date": 1709927540,
            "last_edit_date": 1709931544,
            "question_id": 78129981,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/78129981/logging-error-failed-to-initialize-logging-system-log-messages-may-be-missing",
            "title": "Logging Error: Failed to initialize logging system. Log messages may be missing.?"
        },
        {
            "tags": [
                "python",
                "python-3.x",
                "pycharm"
            ],
            "owner": {
                "account_id": 6823618,
                "reputation": 1062,
                "user_id": 5250196,
                "user_type": "registered",
                "profile_image": "https://i.sstatic.net/1QajQ.jpg?s=256",
                "display_name": "P2000",
                "link": "https://stackoverflow.com/users/5250196/p2000"
            },
            "is_answered": true,
            "view_count": 6085,
            "accepted_answer_id": 72456461,
            "answer_count": 1,
            "score": 63,
            "last_activity_date": 1666193246,
            "creation_date": 1654055104,
            "last_edit_date": 1654143878,
            "question_id": 72456234,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/72456234/why-does-print-i-e-three-dots-in-a-row-print-blank",
            "title": "Why does print(&quot;...&quot;), i.e. three dots in a row, print blank?"
        },
        {
            "tags": [
                "python"
            ],
            "owner": {
                "account_id": 24835532,
                "reputation": 621,
                "user_id": 18714220,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/a-/AOh14GjpNxl2WQc7w30aQ9y641atIyL2lvv3QmWJaerZC04=k-s256",
                "display_name": "Bachir bessei",
                "link": "https://stackoverflow.com/users/18714220/bachir-bessei"
            },
            "is_answered": true,
            "view_count": 165176,
            "protected_date": 1721809033,
            "answer_count": 19,
            "score": 62,
            "last_activity_date": 1721750126,
            "creation_date": 1649198983,
            "last_edit_date": 1673098786,
            "question_id": 71759248,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/71759248/importerror-cannot-import-name-builder-from-google-protobuf-internal",
            "title": "ImportError: cannot import name &#39;builder&#39; from &#39;google.protobuf.internal&#39;"
        },
        {
            "tags": [
                "python",
                "performance",
                "cpython",
                "python-internals",
                "python-3.11"
            ],
            "owner": {
                "account_id": 17476274,
                "reputation": 27057,
                "user_id": 12671057,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/90d2e6942c69df199a95d06e0c8e9a10?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "Kelly Bundy",
                "link": "https://stackoverflow.com/users/12671057/kelly-bundy"
            },
            "is_answered": true,
            "view_count": 9815,
            "accepted_answer_id": 77635068,
            "answer_count": 1,
            "score": 62,
            "last_activity_date": 1702886328,
            "creation_date": 1702214257,
            "last_edit_date": 1702215859,
            "question_id": 77634955,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/77634955/why-is-the-simpler-loop-slower",
            "title": "Why is the simpler loop slower?"
        },
        {
            "tags": [
                "python",
                "flask",
                "jinja2"
            ],
            "owner": {
                "account_id": 15865542,
                "reputation": 1411,
                "user_id": 11447688,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/16e8410a6faec497b5f4eae530cda0a7?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "young_minds1",
                "link": "https://stackoverflow.com/users/11447688/young-minds1"
            },
            "is_answered": true,
            "view_count": 144372,
            "answer_count": 12,
            "score": 61,
            "last_activity_date": 1691384656,
            "creation_date": 1648460099,
            "last_edit_date": 1651468617,
            "question_id": 71645272,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/71645272/importerror-cannot-import-name-markup-from-jinja2",
            "title": "ImportError: cannot import name &#39;Markup&#39; from &#39;jinja2&#39;"
        },
        {
            "tags": [
                "python",
                "openai-api"
            ],
            "owner": {
                "account_id": 19934883,
                "reputation": 817,
                "user_id": 14607802,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/ebb1a082fb58622f567e9f8ba1b480ca?s=256&d=identicon&r=PG&f=y&so-version=2",
                "display_name": "Charmalade",
                "link": "https://stackoverflow.com/users/14607802/charmalade"
            },
            "is_answered": true,
            "view_count": 46769,
            "answer_count": 6,
            "score": 61,
            "last_activity_date": 1717834065,
            "creation_date": 1670380288,
            "last_edit_date": 1683994435,
            "question_id": 74711107,
            "content_license": "CC BY-SA 4.0",
            "link": "https://stackoverflow.com/questions/74711107/openai-api-continuing-conversation-in-a-dialogue",
            "title": "OpenAI API continuing conversation in a dialogue"
        }
    ]
}